
spring :
  datasource:
    url: jdbc:sqlserver://192.168.1.248:1433;databaseName=RestfulAPI
    username: sa
    password: tap@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8083
